// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANa0Vk0gMK7NWpvAM9sljkICePVyBYvSs',
    appId: '1:859992573582:web:bd69346046c8aa85186bdf',
    messagingSenderId: '859992573582',
    projectId: 'plant-28c8f',
    authDomain: 'plant-28c8f.firebaseapp.com',
    storageBucket: 'plant-28c8f.firebasestorage.app',
    measurementId: 'G-NCWG5TJ8ZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuX1xUQZsaPX3ON6Yf-LxRyPX7U67hZf4',
    appId: '1:859992573582:android:7371766dcb8893f0186bdf',
    messagingSenderId: '859992573582',
    projectId: 'plant-28c8f',
    storageBucket: 'plant-28c8f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANa0Vk0gMK7NWpvAM9sljkICePVyBYvSs',
    appId: '1:859992573582:web:07df843348115ed7186bdf',
    messagingSenderId: '859992573582',
    projectId: 'plant-28c8f',
    authDomain: 'plant-28c8f.firebaseapp.com',
    storageBucket: 'plant-28c8f.firebasestorage.app',
    measurementId: 'G-TXSL2H3RX4',
  );
}
